### ISSUE TITLE
Likelihood calculation takes to much time!

### ISSUE THREAD

**Issue by JesperLH** [sfvnDTU/parmugit#1]
Please implement such that only changes are reevaluated, not entire nodeloglikelihood

**Comment by juliankopkalarsen** [comment]
I think this can be fixed by using vectors.

**Comment by JesperLH** [comment]
Hmm great idea

Den 26/02/2015 kl. 10.57 skrev juliankopkalarsen notifications@github.com:

**Comment by juliankopkalarsen** [comment]
There is a problem with the selective update of the likelihood cache. When removing nodes. The caches to be removed is of course known at removal but then it "vanishes" when the node is removed. so we thought to remove it along with the node but then the rest of the update has to assume that the first node in the chain is updated. does that make sense or is there a smarter way to do it.
